# Generated by Django 5.1 on 2024-08-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Input",
            new_name="FileUpload",
        ),
    ]
